os: linux
arch: amd64
dist: xenial

language: node_js
node_js: 
  - lts/*

cache: npm

install: npm ci
script: npm test

deploy: 
  provider: npm
  api_key: $NPM_TOKEN
  email: $NPM_EMAIL
  on:
    tags: true